services:
  - type: web
    name: traveloop
    env: python310
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false